AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DanEmail:
    Type: String
  TonyEmail:
    Type: String

Resources:
  OptimalLineupTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref DanEmail
          Protocol: email
        - Endpoint: !Ref TonyEmail
          Protocol: email