AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: String
  CodeKey:
    Type: String
  AwsKey:
    Type: String
  AwsSecret:
    Type: String
  FanduelApiRoot:
    Type: String
Globals:
  Function:
    MemorySize: 512
    Timeout: 900

Resources:
  MergeDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: src/mergeData/index.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          AWS_KEY: !Ref AwsKey
          AWS_SECRET: !Ref AwsSecret
  ScheduleStateMachinesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: src/scheduleStateMachines/index.handler
      Runtime: nodejs12.x
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 14 * * ? *)
            Input: '{"sports": ["nba", "nhl"]}'
      Environment:
        Variables:
          FANDUEL_API_ROOT: !Ref FanduelApiRoot
          AWS_KEY: !Ref AwsKey
          AWS_SECRET: !Ref AwsSecret