AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: String
  CodeKey:
    Type: String
  AwsKey:
    Type: String
  AwsSecret:
    Type: String
  FanduelApiRoot:
    Type: String
  DanPhoneNumber:
    Type: String
  TonyPhoneNumber:
    Type: String
Globals:
  Function:
    MemorySize: 512
    Timeout: 900

Resources:
  MergeDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: src/mergeData/index.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          AWS_KEY: !Ref AwsKey
          AWS_SECRET: !Ref AwsSecret
  ScheduleStateMachinesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: src/scheduleStateMachines/index.handler
      Runtime: nodejs12.x
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 14 * * ? *)
            Input: '{"sports": ["nba", "nhl"]}'
      Environment:
        Variables:
          FANDUEL_API_ROOT: !Ref FanduelApiRoot
          AWS_KEY: !Ref AwsKey
          AWS_SECRET: !Ref AwsSecret
  DFSOptimizer:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: 'dfs-optimizer-batch'
      RetryStrategy:
        Attempts: 1
      ContainerProperties:
        Image: 062130427086.dkr.ecr.us-east-2.amazonaws.com/dfs-optimizer:latest
        Vcpus: 2
        Memory: 2000
        Privileged: true
        Environment:
          - Name: AWS_KEY
            Value: !Ref AwsKey
          - Name: AWS_SECRET
            Value: !Ref AwsSecret
          - Name: OPTIMIZER_INPUT
            Value: Optimizer Input
      Timeout:
        AttemptDurationSeconds: 3600
  SendOptimalLineupTextsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: src/sendOptimalLineupTexts/index.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          AWS_KEY: !Ref AwsKey
          AWS_SECRET: !Ref AwsSecret
          DAN_PHONE_NUMBER: !Ref DanPhoneNumber
          TONY_PHONE_NUMBER: !Ref TonyPhoneNumber
  DFSPipeline:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: arn:aws:iam::062130427086:role/service-role/StepFunctions-DFSPipeLine-role-1d6983e2
      Fn::Transform:
        Name: AWS::Include
        Parameters:
          Location:
            Fn::Sub: s3://${BucketName}/dfs-pipeline-state-machine-definition.yaml